<?php 

	$goods=array(
		array(
			'title'=>'tov1',
			'price_type'=>'uah',
			'price_val'=>100,
			'discount_type'=>value,
			'discount_value'=>10,
			),
		array(
			'title'=>'tov2',
			'price_type'=>'usd',
			'price_val'=>150,
			'discount_type'=>percent,
			'discount_value'=>10,
			),
		array(
			'title'=>'tov3',
			'price_type'=>'eur',
			'price_val'=>200,
			'discount_type'=>value,
			'discount_value'=>20,
			),
		array(
			'title'=>'tov4',
			'price_type'=>'uah',
			'price_val'=>300,
			'discount_type'=>percent,
			'discount_value'=>10,
			),
		array(
			'title'=>'tov5',
			'price_type'=>'usd',
			'price_val'=>350,
			'discount_type'=>value,
			'discount_value'=>35,
			),
		array(
			'title'=>'tov6',
			'price_type'=>'eur',
			'price_val'=>400,
			'discount_type'=>percent,
			'discount_value'=>20,
			),
		array(
			'title'=>'tov7',
			'price_type'=>'uah',
			'price_val'=>500,
			'discount_type'=>value,
			'discount_value'=>50,
			),
		array(
			'title'=>'tov8',
			'price_type'=>'usd',
			'price_val'=>600,
			'discount_type'=>percent,
			'discount_value'=>15,
			),
		array(
			'title'=>'tov9',
			'price_type'=>'eur',
			'price_val'=>700,
			'discount_type'=>value,
			'discount_value'=>70,
			),
		array(
			'title'=>'tov10',
			'price_type'=>'uah',
			'price_val'=>800,
			'discount_type'=>percent,
			'discount_value'=>25,
			),
);
?>

